### ISSUE TITLE
python hackinsta.py error 

### ISSUE THREAD

**Issue by vshlkshk** [avramit/Instahack#100]
python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'

@avramit 
I am not able to install proxybroker everytime a red text error comes amd when i enterd command hackinsta.py it pops up with this error please help me get out of this
Error.
I am using Termux application on android.
Thank You

**Comment by mohammadaliazizkhani** [comment]
@avramit 
from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'
please help me;

**Comment by MrCreepy04** [comment]
I now the problem and normaly you must make pip install proxybroker but an error is by running this commend! It installs proxybroker and at the end an error occulted

**Comment by surazz2** [comment]
python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybrok
How can i solve this problem? Plz help!!

**Comment by hak1mlukha** [comment]
try using pip3 install proxybroker and python3 instahack.py

**Comment by 07utsavsaxena** [comment]
How to sloved problem python hackinsta.py error and module errors also

**Comment by ebiomidi66** [comment]
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybr
Help me.

**Comment by affanblaze** [comment]
"/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-8_ww4b12/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-_hmqb2mb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-8_ww4b12/pycares/

Its comin like this after writing
Pip3 install proxybroker

**Comment by behnam4854** [comment]
same problem
