### ISSUE TITLE
Proxy broker 

### ISSUE THREAD

**Issue by dvrftm** [avramit/Instahack#113]
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'
$ python3 hackinsta.py fatemehdvv passwords.txt
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'

**Comment by dfmAbbas** [comment]
+1

**Comment by kingHackOfKermanshah** [comment]
dvrftm`s problem,I have too........ Who can help us???

**Comment by surazz2** [comment]
Me too have same problem ho can i solve ?  @dfmAbbas

**Comment by dfmAbbas** [comment]
@surazz2 Use pip3 instead of pip to install packages, and use python3 to run.
