### ISSUE TITLE
just came back to this

### ISSUE THREAD

**Issue by Deyelk** [avramit/Instahack#121]
File "hackinsta.py", line 54
    async def proxything(proxies):
            ^
SyntaxError: invalid syntax

**Comment by hellboyPeep** [comment]
use this command: python3 hackinsta.py username password.list 

Then it is loading the proxies...

**Comment by ebiomidi66** [comment]
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybr
