### ISSUE TITLE
Can you help me out (utf-8 file reading) (old version)

### ISSUE THREAD

**Issue by FunkDaddyXD** [avramit/Instahack#19]
This pops up right after I type the username. Traceback (most recent call last):
  File "hackinsta.py", line 142, in <module>         instabrute = Instabrute(Input('Please enter a username: '))
  File "hackinsta.py", line 34, in __init__          self.loadPasswords()
  File "hackinsta.py", line 48, in loadPasswords
    self.passwords = f.read().splitlines()
  File "/data/data/com.termux/files/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3701446: invalid continuation byte. Not sure what to do.

**Comment by TristonStuart** [comment]
python error?
Reinstall python?

**Comment by avramit** [comment]
Download the new code
