### ISSUE TITLE
No clue whats wrong. 

### ISSUE THREAD

**Issue by tinysmugglercx59** [avramit/instahack#20]
After I enter a username, I get this:

```
[*] 888 Passwords loads successfully

Traceback (most recent call last):
  File "C:\Users\Cat\Desktop\instahack-master\instahack-master\hackinsta.py", line 141, in <module>
    instabrute = Instabrute(Input('Please enter a username: '))
  File "C:\Users\Cat\Desktop\instahack-master\instahack-master\hackinsta.py", line 35, in __init__
    self.IsUserExists()
  File "C:\Users\Cat\Desktop\instahack-master\instahack-master\hackinsta.py", line 79, in IsUserExists
    r = requests.get('https://www.instagram.com/%s/?__a=1' % self.username)
NameError: global name 'requests' is not defined
```

helppp

**Comment by avramit** [comment]
Log says: NameError: global name 'requests' is not defined

The "requests" module is not installed !

To install with pip:
pip install requests

https://pypi.python.org/pypi/requests/2.7.0
