### ISSUE TITLE
No module named

### ISSUE THREAD

**Issue by robertjriga** [avramit/Instahack#21]
I feel like someone tries to gain acces of my phone rather than instahack..
So here is my issue:
`$python hackinsta.py
Traceback (most recent call last):
File "hackinsta.py", line 9, in <module>
import requests
ModuleNotFoundError: No module named 'requests'.

`

**Comment by TristonStuart** [comment]
You have to install requests.
Install Python, make sure pip is installed.
Then in cmd type `pip requests` or `pip install requests`

**Comment by andika04kd** [comment]
ceback (most recent call last):
  File "hackinsta.py", line 142, in <module>
    instabrute = Instabrute(Input('Please enter a username: '))
  File "hackinsta.py", line 34, in __init__
    self.loadPasswords()
  File "hackinsta.py", line 48, in loadPasswords
    self.passwords = f.read().splitlines()
  File "/data/data/com.termux/files/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 344478: invalid continuation byte

How about this?

**Comment by 07utsavsaxena** [comment]
How to solve problem python hackinsta.py error line 2 or module error

**Comment by shhrdgs** [comment]
I have a problem with this please help me
 Traceback (most recent call last):
File "hackinsta.py", line 142, in 
instabrute = Instabrute(Input('Please enter a username: '))
File "hackinsta.py", line 34, in init
self.loadPasswords()
File "hackinsta.py", line 48, in loadPasswords
self.passwords = f.read().splitlines()
File "/data/data/com.termux/files/usr/lib/python3.7/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 4054309: invalid continuation byte
