### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by andika04kd** [avramit/Instahack#22]
Traceback (most recent call last):
  File "hackinsta.py", line 142, in <module>
    instabrute = Instabrute(Input('Please enter a username: '))
  File "hackinsta.py", line 34, in __init__
    self.loadPasswords()
  File "hackinsta.py", line 48, in loadPasswords
    self.passwords = f.read().splitlines()
  File "/data/data/com.termux/files/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 344478: invalid continuation byte

How i am gonna solve this?

**Comment by Prince27842** [comment]
Same here

**Comment by 9aa00** [comment]
f.read

**Comment by avramit** [comment]
Please download the new code
