### ISSUE TITLE
Raised a error even after using pip install requests

### ISSUE THREAD

**Issue by Prince27842** [avramit/Instahack#25]
python hackinsta.py
Please enter a username: h
Traceback (most recent call last):
  File "hackinsta.py", line 142, in <module>
    instabrute = Instabrute(Input('Please enter a username: '))
  File "hackinsta.py", line 34, in __init__
    self.loadPasswords()
  File "hackinsta.py", line 48, in loadPasswords
    self.passwords = f.read().splitlines()
  File "/data/data/com.termux/files/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by 9aa00** [comment]
ecd4ec4c

**Comment by avramit** [comment]
Please download the new code
