### ISSUE TITLE
Help me stuck on last stage !

### ISSUE THREAD

**Issue by Pratikkk** [avramit/Instahack#31]
I'm in last line and raised this error what should i do please help me. and where can i find pass.txt file ?

Traceback (most recent call last):
  File "hackinsta.py", line 143, in <module>
    instabrute = Instabrute(Input('Please enter a username: '))
  File "hackinsta.py", line 37, in __init__
    self.IsUserExists()
  File "hackinsta.py", line 83, in IsUserExists
    print ('[*] User named "%s" not found' % username)
NameError: name 'username' is not defined
$

**Comment by avramit** [comment]
Please download the new code
