### ISSUE TITLE
Don't work help. Http socks 403 Forbidden

### ISSUE THREAD

**Issue by SiBuLbA** [avramit/Instahack#49]
PC, Win10, installed all modules

C:\Users\Илья\Desktop\Instahack-master>python hackinsta.py madiratito22 passwords.txt
[*] Found proxy: <Proxy CA 0.14s [HTTP: High] 142.44.194.14:3128>
[*] 965 passwords loaded successfully
Traceback (most recent call last):
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\socks.py", line 851, in connect
    negotiate(self, dest_addr, dest_port)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\socks.py", line 763, in _negotiate_HTTP
    raise HTTPError(error)
socks.HTTPError: 403: Forbidden

[*] Note: The HTTP proxy server may not be supported by PySocks (must be a CONNECT tunnel proxy)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\socks.py", line 855, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 403: Forbidden

[*] Note: The HTTP proxy server may not be supported by PySocks (must be a CONNECT tunnel proxy)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000017432B37F98>: Failed to establish a new connection: Socket error: 403: Forbidden

[*] Note: The HTTP proxy server may not be supported by PySocks (must be a CONNECT tunnel proxy)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /madiratito22/?__a=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000017432B37F98>: Failed to establish a new connection: Socket error: 403: Forbidden\n\n[*] Note: The HTTP proxy server may not be supported by PySocks (must be a CONNECT tunnel proxy)',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hackinsta.py", line 127, in <module>
    bruteforce = Instabrute(args.username, passwords)
  File "hackinsta.py", line 34, in __init__
    if not self.userExists():
  File "hackinsta.py", line 42, in userExists
    r = requests.get('https://www.instagram.com/%s/?__a=1' % self.username)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Илья\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /madiratito22/?__a=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000017432B37F98>: Failed to establish a new connection: Socket error: 403: Forbidden\n\n[*] Note: The HTTP proxy server may not be supported by PySocks (must be a CONNECT tunnel proxy)',))

**Comment by Epsil0n31** [comment]
Try pip install requests
pip install requests -r proxybroke pycares aiodns asyncio

**Comment by avramit** [comment]
Just try to restart the script.

**Comment by praveensinha16** [comment]
Same Issue. 
Need urgent help for the resolution. Please suggest.
