### ISSUE TITLE
Try to run on android

### ISSUE THREAD

**Issue by uv7** [avramit/Instahack#50]
I m facing this afterall commands...😭
![screenshot_20180227-025517](https://user-images.githubusercontent.com/36864445/36696347-d61c2228-1b3b-11e8-8401-7bfb819c9c70.png)

**Comment by Epsil0n31** [comment]
Execute pip install requests and again

**Comment by uv7** [comment]
Did it....though facing this errror!

**Comment by oliveiraLuan** [comment]
I am with same problem :( , Do you have obtained a solution?

**Comment by uv7** [comment]
No buddy...😭

**Comment by avramit** [comment]
@oliveiraLuan @uv7 Try to run on pc

**Comment by sucklaugh** [comment]
I think the reason why it causes error because of the modules needed and i can't install those modules.

**Comment by uv7** [comment]
@avaramit actually i m not more avare abt this b
coz my main stream is medical so can u plz tell.me.how or i do have to apply same.codes in pc?

**Comment by uv7** [comment]
I tried on my pc and i installed remote terminal bt it ask for ssh n i no more good in this things so help needed!...😣

**Comment by avramit** [comment]
@uv7 no no!, dont use ssh, install python on your pc and run the file

**Comment by uv7** [comment]
Python how can i install it on pc i mean can u suggest me pc software

**Comment by uv7** [comment]
Ok i got it how to install...let me check that method out

**Comment by Epsil0n31** [comment]
Apt install cffi 
pip install aiodns
pip install pycares 
pip install proxybroker or
pip install -r request pycares aiodns pycares proxybroker and again...i resolved that

**Comment by Epsil0n31** [comment]
Apt install cffi 
pip install aiodns
pip install pycares 
pip install proxybroker or
pip install -r request pycares aiodns pycares proxybroker and again...i resolved that

**Comment by avramit** [comment]
@Epsil0n31 thank you

**Comment by uv7** [comment]
Wait let me check tht out

**Comment by uv7** [comment]
@Epsil0n31 i m also fascing "unable to locate cffi" other thi gs are ok except this command "pip install -r request pycares aiodns pycares proxybroker" errno 2 relating request

**Comment by uv7** [comment]
Things*

**Comment by uv7** [comment]
Guys i d9nt knw commands to be used in python help.me.plzzz

**Comment by Epsil0n31** [comment]
@uv7 sorry me was pip install cffi and try run pip install - r requests aiodns pycares proxybroker

**Comment by uv7** [comment]
I got this after using pip install cffi

**Comment by uv7** [comment]
![screenshot_20180302-164900](https://user-images.githubusercontent.com/36864445/36896744-c1fbb754-1e0b-11e8-9acf-cb85715b5dc5.png)

**Comment by Epsil0n31** [comment]
`apt install python3`
`apt install python3-dev`
`apt install gcc`
And try again `pip install cffi`

**Comment by oliveiraLuan** [comment]
![e392ee7f-6199-4ea2-8777-8c39d4566c88](https://user-images.githubusercontent.com/30847671/36906433-aad98958-1e14-11e8-8d80-cf65c20eaad6.jpeg)
After install cffi , show me these error. :(

**Comment by Epsil0n31** [comment]
`pip install pycares`and run `python hackinsta.py`

**Comment by nis130** [comment]
I

**Comment by oliveiraLuan** [comment]
pip install proxybroker

**Comment by uv7** [comment]
Error keeps on.....nthing changed even after every codings......i need codes to figure it out...😢

**Comment by madafumaddy** [comment]
python3.6 hackinsta.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pycares/__init__.py", line 5, in <module>
    from ._core import *
ImportError: dlopen failed: cannot locate symbol "getservbyport_r" referenced by "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pycares/_core.cpython-36m.so"...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/__init__.py", line 28, in <module>
    from .proxy import Proxy  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/proxy.py", line 11, in <module>
    from .resolver import Resolver
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/resolver.py", line 8, in <module>
    import aiodns
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/aiodns/__init__.py", line 7, in <module>                import pycares                                            File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pycares/__init__.py", line 7, in <module>               from ._cfficore import *                                ModuleNotFoundError: No module named 'pycares._cfficore'   
This error I get while running python3.6 hackinsta.py

**Comment by dungeon-master69** [comment]
Python3, python3-dev package not found. Cant install proxybroker please help

**Comment by dungeon-master69** [comment]
c/_cffi_backend.c:2:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^~~~~~~~~~
    1 error generated.
    error: command 'aarch64-linux-android-clang' failed with exit status 1

**Comment by dungeon-master69** [comment]
Help me

**Comment by ritikzdiamond** [comment]
dungeon-master69  install python-dev
apt-get install python-dev

**Comment by kapilss** [comment]
=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/data/data/com.termux/files/usr/include/python3.6m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.6/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-yol3k6hy/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-fcdp1hta-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-yol3k6hy/cffi/
  
help me always showing this..

**Comment by DanTheTechMan1** [comment]
Can someone help me 2

**Comment by sapisusu** [comment]
$ python hackinsta.py                            Traceback (most recent call last):                 File "hackinsta.py", line 10, in <module>          from proxybroker import Broker               ModuleNotFoundError: No module named 'proxybroker'

**Comment by JPHACKER2k18** [comment]
Use gnu/root debian

**Comment by xHackxhackx** [comment]
I have problem with this: Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 114, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'.   Can someone help me pls🥺

**Comment by xHackxhackx** [comment]
Anyone help me?
