### ISSUE TITLE
Not found - pycares - termux

### ISSUE THREAD

**Issue by Pratham2004** [avramit/Instahack#66]
/data/data/com.termux/files/usr/tmp/pip-build-2bhnujru/pycares/

How to install this module?

Plsss help me

**Comment by avramit** [comment]
look at the readme file and install all the requierd modules

**Comment by hummel37** [comment]
I have the Error code
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pycares/__init__.py", line 5, in <module>
    from ._core import *
ImportError: dlopen failed: cannot locate symbol "getservbyport_r" referenced by "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pycares/_core.cpython-36m.so"...
                                                        During handling of the above exception, another exception occurred:                                             
Traceback (most recent call last):                        File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/__init__.py", line 28, in <module>
    from .proxy import Proxy  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/proxy.py", line 11, in <module>     from .resolver import Resolver
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/resolver.py", line 8, in <module>                                                           import aiodns                                         File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/aiodns/__init__.py", line 7, in <module>        import pycares
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pycares/__init__.py", line 7, in <module>       from ._cfficore import *
ModuleNotFoundError: No module named 'pycares._cfficore'
