### ISSUE TITLE
hi im newbie here, can you help me? 

### ISSUE THREAD

**Issue by mahawkx** [avramit/Instahack#72]
i get this error
$ python2 hackinsta.py
  File "hackinsta.py", line 54
    async def proxything(proxies):
            ^
SyntaxError: invalid syntax
$
what should i do?

**Comment by mahawkx** [comment]
i try it on termux android btw

**Comment by avramit** [comment]
why 99% of the users use Android?
lol
i can't answer on your question cause the script never checked on Android

**Comment by hamzadiaz** [comment]
I would run it on Kali Linux or Ubuntu.

**Comment by ShubhamShukla29** [comment]
Termux showing these errors
python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker

**Comment by ShubhamShukla29** [comment]
$ python2 hackinsta.py
  File "hackinsta.py", line 54
    async def proxything(proxies):
            ^
SyntaxError: invalid syntax

**Comment by mostwantedha** [comment]
Hi bro thank you for crack instagram script i have a problem to install the script but i install all of the README.md in kali linux please help me ....i need this....thanks

**Comment by mostwantedha** [comment]
~/Downloads/Instahack# python hackinsta.py 
  File "hackinsta.py", line 54
    async def proxything(proxies):
            ^
SyntaxError: invalid syntax

**Comment by mostwantedha** [comment]
oh yes i find it use this for run script:
python3 hackinsta.py username passwords_file
its work
:+1:

**Comment by mostwantedha** [comment]
ooppss i have another problem :( 
my username is true but.....

~/Downloads/Instahack# python3 hackinsta.py hamidsamsam passwords.txt 
[*] Loading proxies
[*] Proxy: <Proxy DE 0.31s [HTTP: Transparent] 136.243.145.143:80>
[*] 8 passwords loaded successfully
[*] Can't find user named "hamidsamsam"
