### ISSUE TITLE
hackinsta.py Line 165

### ISSUE THREAD

**Issue by DontAtMe** [avramit/Instahack#74]
I am trying to load the code but am confronted with this error
[*] Loading proxies
[*] Proxy: <Proxy HK 0.85s [HTTP: High] 47.52.231.140:8080>
Traceback (most recent call last):
  File "hackinsta.py", line 165, in <module>
    passwords = file.read().splitlines()
  File "C:\Program Files (x86)\Python36-32\lib\codecs.py", line 698, in read
    return self.reader.read(size)
  File "C:\Program Files (x86)\Python36-32\lib\codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 418041: invalid start byte

**Comment by DontAtMe** [comment]
Update: I installed iconv_codecs but now have a slightly different error
*] Loading proxies
[*] Proxy: <Proxy HK 1.36s [HTTP: High] 47.91.139.78:80>
Traceback (most recent call last):
  File "hackinsta.py", line 165, in <module>
    passwords = file.read().splitlines()
  File "C:\Program Files (x86)\Python36-32\lib\codecs.py", line 698, in read
    return self.reader.read(size)
  File "C:\Program Files (x86)\Python36-32\lib\codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 418041: invalid start byte

**Comment by CoryTDC** [comment]
Make sure your running this on python3.6

**Comment by DontAtMe** [comment]
yes i am running python 3.6
