### ISSUE TITLE
Proxy Error (Ssl cert verify error) (Old version)

### ISSUE THREAD

**Issue by NexifyUS** [avramit/Instahack#8]
I Went To Use Proxys and Pressed "y" and Got The Following Error

Traceback (most recent call last):
  File "hackinsta.py", line 149, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 111, in Login
    r = sess.get('https://www.instagram.com/') 
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error(104, 'Connection reset by peer')))

**Comment by firebreed** [comment]
Bad or dead proxy, probably > Cannot connect to proxy.', error(104, 'Connection reset by peer')
